### ISSUE TITLE
Tracking of docker-hub automated build changes

### ISSUE THREAD

**Issue by rtrauntvein** [cachethq/Docker#7]
This is to help track what needs to happen to switch the automated builds on docker hub to this repository with minimal interruption. 

- [x] Delete existing docker hub build `cachethq/cachet`
- [x] Create new docker hub build `cachethq/cachet:base` pointed at this repository branch `base`
- [x] Make sure Dockerfiles for version releases use `FROM cachethq/cachet:base`
- [x] Create new docker hub build `cachethq/cachet:1.1.1` pointed at this repository tag `v1.1.1`
- [x] Create new docker hub build `cachethq/cachet:latest` pointed at this repository tag `v1.1.1`
- [x] Create new docker hub build `cachethq/cachet:1.2` pointed at this repository branch `v1.2-dev`

**Comment by rtrauntvein** [comment]
@cachethq/docker does this look right? Did I miss anything here?

**Comment by wfjsw** [comment]
base have an commit-id tag :p
just givebup 1.1.1 and move 1.2 to master

**Comment by rtrauntvein** [comment]
Do we need to keep that ? Why not just use :base

**Comment by wfjsw** [comment]
@rtrauntvein That causes cache night-mare

**Comment by rtrauntvein** [comment]
How are you doing CI?

**Comment by wfjsw** [comment]
@rtrauntvein It is a free system in China provides advanced Automatic Build and Deploy functions.
I just press the 'build now' :p
